theme = "emacs"

[editor]
idle-timeout = 50
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"C-a" = "goto_first_nonwhitespace"
"C-e" = "goto_line_end"

[keys.insert]
"C-a" = "goto_first_nonwhitespace"
"C-f" = "normal_mode"
