theme = "catppuccin_macchiato"

[editor]
auto-pairs = false
completion-trigger-len = 3
idle-timeout = 200
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false  # enable finding dotfiles

[keys.normal]
# makes `a` function like `a` in vim
# instead of starting a new selection
"a" = [
  "move_char_right",
  "insert_mode"
]
"C-a" = "goto_first_nonwhitespace"
"C-e" = "goto_line_end"

[keys.normal."space"]
"o" = "file_picker_in_current_buffer_directory"

[keys.insert]
"C-a" = "goto_first_nonwhitespace"
"C-e" = [
  # Need to move 1 char right because in insert mode
  # goto_line_end moves one char back from the end of the line.
  "goto_line_end",
  "move_char_right"
]
"C-f" = "normal_mode"
"C- " = "completion"

[keys.select]
"C-a" = "goto_first_nonwhitespace"
"C-e" = "goto_line_end"
"C-f" = "normal_mode"
