theme = "monokai_pro"

[editor]
idle-timeout = 100
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false  # enable finding dotfiles

[keys.normal]
"C-a" = "goto_first_nonwhitespace"
"C-e" = "goto_line_end"

[keys.insert]
"C-a" = "goto_first_nonwhitespace"
"C-f" = "normal_mode"
